FROM pypy:latest
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/kubectl
RUN pip install elasticsearch
COPY ./src/monitor.py .
CMD ["pypy", "monitor.py"]