kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobmonitor-role
  namespace: elk
subjects:
- kind: ServiceAccount
  name: jobmonitor-role
  namespace: elk
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobmonitor-role
  namespace: elk