name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: guestros/kubernetes-job-monitor-simple:latest
      -
        name: Build and push pypy
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: guestros/kubernetes-job-monitor-simple:pypy-latest
          dockerfile: Dockerfile.pypy
